version: '2'

services:
  kong:
    image: kong:2.8.1-alpine
    container_name: kong
    depends_on:
      - kong-database
      - kong-migration
      
    expose:
      - "8001"
      - "8444"
      - "8000"
      - "8443"
    restart: always
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-database
      KONG_PG_PORT:          5432
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS:          basic-auth, key-auth, rate-limiting, prometheus, proxy-cache, oauth2

      # VIRTUAL_HOST: kong.localhost
      # VIRTUAL_PORT: 8000
      # LETSENCRYPT_HOST: kong.localhost

    networks: 
    - webproxy
    - kong_network
    
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    volumes:
      - kong_datastore:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpass
      POSTGRES_HOST_AUTH_METHOD: trust
    networks: 
      - webproxy
      - kong_network
  
  kong-migration:
    image: kong:2.8.1-alpine
    container_name: kong-migration
    command: "kong migrations up"
    restart: on-failure
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-database
      KONG_PG_PASSWORD:      kongpass
    depends_on:
      - kong-database
    networks: 
      - webproxy
      - kong_network
      
  konga:
    container_name: konga
    image: pantsel/konga
    restart: always

    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga-database
      DB_USER: konga 
      DB_PASSWORD: kongpass 
      DB_DATABASE: konga_db
      NODE_ENV: development

      # VIRTUAL_HOST: konga.localhost
      # VIRTUAL_PORT: 1337
      # LETSENCRYPT_HOST: konga.localhost

    expose:
    - "1337"

    networks: 
      - webproxy
      - kong_network
  
  konga-database:
    image: postgres:9.6
    container_name: konga-database
    volumes:
      - konga_database:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: konga_db
      POSTGRES_USER: konga
      POSTGRES_PASSWORD: kongapass
      POSTGRES_HOST_AUTH_METHOD: trust 
    networks: 
      - webproxy
      - kong_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/promtheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - "9090"
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    expose:
      - "9100"
    restart: always

volumes:
  kong_datastore:
  konga_database:
  prometheus_data:
  
networks:
  webproxy:
    external:
      name: webproxy
  kong_network:
    external:
      name: kong_network